import type { Metadata } from 'next';
import { Geist, Geist_Mono, Josefin_Sans } from 'next/font/google';

import './globals.css';
import Navbar from '@/components/navbar';

export const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  variable: '--font-josefin',
});

export const metadata: Metadata = {
  title: 'Aurora - Book Luxury Rooms',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefinSans.variable} antialiased bg-indigo-950 min-h-screen flex flex-col relative`}
      >
        <Navbar />

        <main className="max-w-7xl mx-auto flex flex-col w-full flex-1">
          {children}
        </main>
      </body>
    </html>
  );
}
